display items count:
  general: {fallback: 10, maximum: 100}
  youtube-search results: {maximum: 15}
# color pallete: # Coming later
#   COLOR 1: 
#   COLOR 2: 
#   COLOR 3: 
#   COLOR 4: 
#   COLOR 5: 
#   COLOR 6: 
download:
  downloads folder: ~/Music
  make a separate mariana folder within "downloads folder": true
  quality:
    audio only: 1
    video with audio: {audio: 1, video: 1}
  type: video
include music folder in library: true
loglevel: 3
maximum youtube-search results count: 15
show about: true
show banner: true
visible: true
editor path: C:\WINDOWS\system32\notepad.exe
