first_boot = true
isdev = true

[about]
author = "vivojay"
date = "27-11-2012"
title = "Mariana CLI Music Player"

[ver]
maj = 0
min = 4
rel = 2

[system_settings]
supported_file_types = [
    ".wav",
    ".mp3",
]
enforce_os_requirement = true
