#=====================================================================
# PLEASE DO NOT TOUCH THIS FILE
# IT ISN'T EXACTLY MEANT TO BE MODIFIED, BUT YOU MAY STILL DO IT...
#=====================================================================

first_boot = true
isdev = true

[about]
author = "vivojay"
date = "19-01-2021"
title = "Mariana CLI Music Player"

[ver]
maj = 0
min = 6
rel = 0

[system_settings]
enable_best_quality_downloads = 1
enforce_os_requirement = true
max_wait_limit_to_get_song_length = 15
supported_file_types = [ ".wav", ".mp3",]
mariana_dl_dir = "MarianaPlayer"
brave_paths = [
    "C:\\Program Files\\BraveSoftware\\Brave-Browser\\Application\\brave.exe",
    "C:\\Program Files (x86)\\BraveSoftware\\Brave-Browser\\Application\\brave.exe",
]
max_recents_size=10_000_000 # 10 mil
supported_python_versions = [[3, 10], [3, 9], [3, 8], [3, 7], ]
